//
//  CueIconGeometry.swift
//  Cue Studio
//

import SwiftUI

// Generated by design/cue-v29/tools/generate_cue_icons.py from the icon SVGs: do not edit by hand.

/// The shapes of the icon set on its 24 × 24 grid, as SVG path data, and the stroke rule that draws them.
nonisolated enum CueIconGeometry {
    /// One piece of an icon: a path, and whether it is drawn with a fill, a stroke or both.
    struct Element: Sendable {
        let path: Path
        let filled: Bool
        let stroked: Bool
        /// A closed shape can be filled when the icon is "on" (a marked best take).
        let closed: Bool
        /// A dash pattern in grid units (dotted lines); nil for a solid one.
        let dash: [CGFloat]?

        init(_ data: String, filled: Bool, stroked: Bool, closed: Bool, dash: [CGFloat]? = nil) {
            self.path = SVGPathParser.path(from: data)
            self.filled = filled
            self.stroked = stroked
            self.closed = closed
            self.dash = dash
        }
    }

    /// The grid every icon is drawn on.
    static let grid: CGFloat = 24

    /// The stroke stays about 1.6 pt wherever the icon is drawn (v29): `1.6 × 24 / size` grid units, between 1.7
    /// and 3.4 so a big icon doesn't go hairline and a tiny one doesn't clot.
    static let renderedStroke: CGFloat = 1.6
    static let strokeGridRange: ClosedRange<CGFloat> = 1.7...3.4

    /// The stroke in grid units for an icon drawn at `size` points.
    static func strokeInGridUnits(forSize size: CGFloat) -> CGFloat {
        guard size > 0 else { return strokeGridRange.lowerBound }
        return min(strokeGridRange.upperBound, max(strokeGridRange.lowerBound, renderedStroke * grid / size))
    }

    /// The stroke in points for an icon drawn at `size` points.
    static func strokeWidth(forSize size: CGFloat) -> CGFloat {
        strokeInGridUnits(forSize: size) * size / grid
    }

    static func elements(for icon: CueIcon) -> [Element] {
        all[icon] ?? []
    }

    private static let all: [CueIcon: [Element]] = [
        .dictate: [
            .init("M12 3h0a3 3 0 0 1 3 3v5a3 3 0 0 1 -3 3h0a3 3 0 0 1 -3 -3v-5a3 3 0 0 1 3 -3z", filled: false, stroked: true, closed: true),
            .init("M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21", filled: false, stroked: true, closed: false),
        ],
        .hooks: [
            .init("M9 6.5v7a4.5 4.5 0 0 0 9 0v-2.5M18 11l-2.3 2.3", filled: false, stroked: true, closed: false),
            .init("M7.2 4.2a1.8 1.8 0 1 0 3.6 0a1.8 1.8 0 1 0 -3.6 0z", filled: true, stroked: false, closed: true),
        ],
        .importText: [
            .init("M3.5 12h9.5M10 8.8l3.2 3.2-3.2 3.2", filled: false, stroked: true, closed: false),
            .init("M13.5 4h5A1.5 1.5 0 0 1 20 5.5v13a1.5 1.5 0 0 1-1.5 1.5h-5", filled: false, stroked: true, closed: false),
        ],
        .needAnIdea: [
            .init("M9.2 18h5.6M10.2 21h3.6", filled: false, stroked: true, closed: false),
            .init("M12 3a6 6 0 0 0-3.4 10.9c.6.4.9 1.1.9 1.8v.3h5v-.3c0-.7.3-1.4.9-1.8A6 6 0 0 0 12 3z", filled: false, stroked: true, closed: true),
            .init("M12.00 6.50C12.23 8.44 12.96 9.17 14.90 9.40C12.96 9.63 12.23 10.36 12.00 12.30C11.77 10.36 11.04 9.63 9.10 9.40C11.04 9.17 11.77 8.44 12.00 6.50Z", filled: true, stroked: false, closed: true),
        ],
        .new: [
            .init("M12 5v14M5 12h14", filled: false, stroked: true, closed: false),
        ],
        .search: [
            .init("M4.3 10.5a6.2 6.2 0 1 0 12.4 0a6.2 6.2 0 1 0 -12.4 0z", filled: false, stroked: true, closed: true),
            .init("M15.2 15.2l4.6 4.6", filled: false, stroked: true, closed: false),
        ],
        .sparkAi: [
            .init("M11 4C11.6 9.6 13.4 11.4 19 12C13.4 12.6 11.6 14.4 11 20C10.4 14.4 8.6 12.6 3 12C8.6 11.4 10.4 9.6 11 4Z", filled: false, stroked: true, closed: true),
            .init("M19.00 1.90C19.23 3.84 19.96 4.57 21.90 4.80C19.96 5.03 19.23 5.76 19.00 7.70C18.77 5.76 18.04 5.03 16.10 4.80C18.04 4.57 18.77 3.84 19.00 1.90Z", filled: true, stroked: false, closed: true),
        ],
        .writeIt: [
            .init("M14.2 5.3l4.5 4.5L9 19.5H4.5V15z", filled: false, stroked: true, closed: true),
            .init("M12.2 7.3l4.5 4.5", filled: false, stroked: true, closed: false),
            .init("M6.00 2.10C6.25 4.18 7.02 4.95 9.10 5.20C7.02 5.45 6.25 6.22 6.00 8.30C5.75 6.22 4.98 5.45 2.90 5.20C4.98 4.95 5.75 4.18 6.00 2.10Z", filled: true, stroked: false, closed: true),
        ],
        .adjust: [
            .init("M4.5 12a7.5 7.5 0 1 0 15 0a7.5 7.5 0 1 0 -15 0z", filled: false, stroked: true, closed: true),
            .init("M12 4.5a7.5 7.5 0 0 0 0 15z", filled: true, stroked: false, closed: true),
        ],
        .audio: [
            .init("M9 18V5.5l10-2V15", filled: false, stroked: true, closed: false),
            .init("M4 18a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0z", filled: false, stroked: true, closed: true),
            .init("M14 15.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0z", filled: false, stroked: true, closed: true),
        ],
        .captions: [
            .init("M5.5 5h13a2.5 2.5 0 0 1 2.5 2.5v9a2.5 2.5 0 0 1 -2.5 2.5h-13a2.5 2.5 0 0 1 -2.5 -2.5v-9a2.5 2.5 0 0 1 2.5 -2.5z", filled: false, stroked: true, closed: true),
            .init("M6.5 12.5h5M13.5 12.5h4M6.5 15.5h8", filled: false, stroked: true, closed: false),
        ],
        .commentCard: [
            .init("M5 4.5h14A1.5 1.5 0 0 1 20.5 6v9a1.5 1.5 0 0 1-1.5 1.5h-9l-4.5 3.5v-3.5H5A1.5 1.5 0 0 1 3.5 15V6A1.5 1.5 0 0 1 5 4.5z", filled: false, stroked: true, closed: true),
            .init("M10.5 8.2v4.6l3.8-2.3z", filled: false, stroked: true, closed: true),
        ],
        .editCut: [
            .init("M4 6.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0z", filled: false, stroked: true, closed: true),
            .init("M4 17.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0z", filled: false, stroked: true, closed: true),
            .init("M8.6 7.9L19.5 17M8.6 16.1L19.5 7", filled: false, stroked: true, closed: false),
        ],
        .filters: [
            .init("M4 10a5.5 5.5 0 1 0 11 0a5.5 5.5 0 1 0 -11 0z", filled: false, stroked: true, closed: true),
            .init("M9 14a5.5 5.5 0 1 0 11 0a5.5 5.5 0 1 0 -11 0z", filled: false, stroked: true, closed: true),
        ],
        .smartEdit: [
            .init("M4.5 19.5L14 10M12.5 8.5l3 3", filled: false, stroked: true, closed: false),
            .init("M17.50 2.40C17.80 4.95 18.75 5.90 21.30 6.20C18.75 6.50 17.80 7.45 17.50 10.00C17.20 7.45 16.25 6.50 13.70 6.20C16.25 5.90 17.20 4.95 17.50 2.40Z", filled: true, stroked: false, closed: true),
            .init("M20.60 9.90C20.75 11.17 21.23 11.65 22.50 11.80C21.23 11.95 20.75 12.43 20.60 13.70C20.45 12.43 19.97 11.95 18.70 11.80C19.97 11.65 20.45 11.17 20.60 9.90Z", filled: true, stroked: false, closed: true),
        ],
        .text: [
            .init("M5 7V5h14v2M12 5v14M9.5 19h5", filled: false, stroked: true, closed: false),
        ],
        .countdown: [
            .init("M5 13.5a7 7 0 1 0 14 0a7 7 0 1 0 -14 0z", filled: false, stroked: true, closed: true),
            .init("M12 13.5V10M10 3h4M18.2 6.8l1.3-1.3", filled: false, stroked: true, closed: false),
        ],
        .flipCamera: [
            .init("M4.95 9.43A7.5 7.5 0 0 1 19.05 9.43", filled: false, stroked: true, closed: false),
            .init("M19.05 14.57A7.5 7.5 0 0 1 4.95 14.57", filled: false, stroked: true, closed: false),
            .init("M18.6 5.8l.6 3.1-3.1.6M5.4 18.2l-.6-3.1 3.1-.6", filled: false, stroked: true, closed: false),
            .init("M9.8 12a2.2 2.2 0 1 0 4.4 0a2.2 2.2 0 1 0 -4.4 0z", filled: true, stroked: false, closed: true),
        ],
        .followsVoice: [
            .init("M6 10v3M9 7.5v8M12 9v5M15 6v11M18 10v3", filled: false, stroked: true, closed: false),
            .init("M4 20.5h16", filled: false, stroked: true, closed: false),
        ],
        .mirrorText: [
            .init("M12 3.5v17", filled: false, stroked: true, closed: false, dash: [1.6, 2.6]),
            .init("M9 7.5L4.5 12 9 16.5zM15 7.5l4.5 4.5-4.5 4.5z", filled: false, stroked: true, closed: true),
        ],
        .readingLine: [
            .init("M7.5 6.5h11M7.5 17.5h8", filled: false, stroked: true, closed: false),
            .init("M6 12h14.5", filled: false, stroked: true, closed: false),
            .init("M1.9 12a1.9 1.9 0 1 0 3.8 0a1.9 1.9 0 1 0 -3.8 0z", filled: true, stroked: false, closed: true),
        ],
        .speed: [
            .init("M4.6 17a7.6 7.6 0 1 1 14.8 0", filled: false, stroked: true, closed: false),
            .init("M12 15.5l3.6-4.4", filled: false, stroked: true, closed: false),
            .init("M14.5 10.1a1.9 1.9 0 1 0 3.8 0a1.9 1.9 0 1 0 -3.8 0z", filled: true, stroked: false, closed: true),
            .init("M10.7 15.5a1.3 1.3 0 1 0 2.6 0a1.3 1.3 0 1 0 -2.6 0z", filled: true, stroked: false, closed: true),
        ],
        .steadyScroll: [
            .init("M4 7h10M4 12h10M4 17h6.5", filled: false, stroked: true, closed: false),
            .init("M18.5 5.5v13M16 16l2.5 2.5L21 16", filled: false, stroked: true, closed: false),
        ],
        .stop: [
            .init("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0z", filled: false, stroked: true, closed: true),
            .init("M10.4 9h3.2a1.4 1.4 0 0 1 1.4 1.4v3.2a1.4 1.4 0 0 1 -1.4 1.4h-3.2a1.4 1.4 0 0 1 -1.4 -1.4v-3.2a1.4 1.4 0 0 1 1.4 -1.4z", filled: true, stroked: false, closed: true),
        ],
        .celebrations: [
            .init("M12 3.5v3.2M12 17.3v3.2M3.5 12h3.2M17.3 12h3.2M6 6l2.2 2.2M15.8 15.8L18 18M6 18l2.2-2.2M15.8 8.2L18 6", filled: false, stroked: true, closed: false),
            .init("M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z", filled: true, stroked: false, closed: true),
        ],
        .cleanVoice: [
            .init("M4 12h2M8 9v6M11 6.5v11M14 9v6", filled: false, stroked: true, closed: false),
            .init("M18.50 4.70C18.80 7.25 19.75 8.20 22.30 8.50C19.75 8.80 18.80 9.75 18.50 12.30C18.20 9.75 17.25 8.80 14.70 8.50C17.25 8.20 18.20 7.25 18.50 4.70Z", filled: true, stroked: false, closed: true),
            .init("M17.1 16a1.4 1.4 0 1 0 2.8 0a1.4 1.4 0 1 0 -2.8 0z", filled: true, stroked: false, closed: true),
        ],
        .haptics: [
            .init("M10.5 3.5h3a2.5 2.5 0 0 1 2.5 2.5v12a2.5 2.5 0 0 1 -2.5 2.5h-3a2.5 2.5 0 0 1 -2.5 -2.5v-12a2.5 2.5 0 0 1 2.5 -2.5z", filled: false, stroked: true, closed: true),
            .init("M4.5 8.5v7M19.5 8.5v7", filled: false, stroked: true, closed: false),
        ],
        .margins: [
            .init("M5.5 4v16M18.5 4v16", filled: false, stroked: true, closed: false),
            .init("M9 9h6M9 12.5h6M9 16h4", filled: false, stroked: true, closed: false),
        ],
        .remote: [
            .init("M10 3h4a3 3 0 0 1 3 3v12a3 3 0 0 1 -3 3h-4a3 3 0 0 1 -3 -3v-12a3 3 0 0 1 3 -3z", filled: false, stroked: true, closed: true),
            .init("M10.2 8a1.8 1.8 0 1 0 3.6 0a1.8 1.8 0 1 0 -3.6 0z", filled: true, stroked: false, closed: true),
            .init("M10 13h4M10 16h4", filled: false, stroked: true, closed: false),
        ],
        .starrySky: [
            .init("M9.50 3.90C10.03 8.32 11.68 9.97 16.10 10.50C11.68 11.03 10.03 12.68 9.50 17.10C8.97 12.68 7.32 11.03 2.90 10.50C7.32 9.97 8.97 8.32 9.50 3.90Z", filled: true, stroked: false, closed: true),
            .init("M17.50 2.50C17.74 4.51 18.49 5.26 20.50 5.50C18.49 5.74 17.74 6.49 17.50 8.50C17.26 6.49 16.51 5.74 14.50 5.50C16.51 5.26 17.26 4.51 17.50 2.50Z", filled: true, stroked: false, closed: true),
            .init("M15.5 17a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0z", filled: true, stroked: false, closed: true),
            .init("M3.9 19.5a1.1 1.1 0 1 0 2.2 0a1.1 1.1 0 1 0 -2.2 0z", filled: true, stroked: false, closed: true),
        ],
        .textSize: [
            .init("M3.5 7h9M8 7v12M14 12h6.5M17.25 12v7", filled: false, stroked: true, closed: false),
        ],
        .volume: [
            .init("M4.5 9.5h3L12 5.5v13l-4.5-4H4.5z", filled: false, stroked: true, closed: true),
            .init("M15.5 9.2a4 4 0 0 1 0 5.6M18 6.8a7.5 7.5 0 0 1 0 10.4", filled: false, stroked: true, closed: false),
        ],
        .profile: [
            .init("M8.4 8.5a3.6 3.6 0 1 0 7.2 0a3.6 3.6 0 1 0 -7.2 0z", filled: false, stroked: true, closed: true),
            .init("M5 20.5c.9-3.9 3.6-6 7-6s6.1 2.1 7 6", filled: false, stroked: true, closed: false),
        ],
        .record: [
            .init("M3.5 12a8.5 8.5 0 1 0 17 0a8.5 8.5 0 1 0 -17 0z", filled: false, stroked: true, closed: true),
            .init("M7.6 12a4.4 4.4 0 1 0 8.8 0a4.4 4.4 0 1 0 -8.8 0z", filled: true, stroked: false, closed: true),
        ],
        .scripts: [
            .init("M14.5 3H6.5A1.5 1.5 0 0 0 5 4.5v15A1.5 1.5 0 0 0 6.5 21h11a1.5 1.5 0 0 0 1.5-1.5V7.5z", filled: false, stroked: true, closed: true),
            .init("M14.5 3v4.5H19", filled: false, stroked: true, closed: false),
            .init("M8.5 12h7M8.5 15.5h4.5", filled: false, stroked: true, closed: false),
        ],
        .settings: [
            .init("M4 8h2.6M11.4 8H20M4 16h9.1M17.9 16H20", filled: false, stroked: true, closed: false),
            .init("M6.6 8a2.4 2.4 0 1 0 4.8 0a2.4 2.4 0 1 0 -4.8 0z", filled: false, stroked: true, closed: true),
            .init("M13.1 16a2.4 2.4 0 1 0 4.8 0a2.4 2.4 0 1 0 -4.8 0z", filled: false, stroked: true, closed: true),
        ],
        .takes: [
            .init("M8 3.5h10.5A1.5 1.5 0 0 1 20 5v10.5", filled: false, stroked: true, closed: false),
            .init("M6.5 7h8a2.5 2.5 0 0 1 2.5 2.5v9a2.5 2.5 0 0 1 -2.5 2.5h-8a2.5 2.5 0 0 1 -2.5 -2.5v-9a2.5 2.5 0 0 1 2.5 -2.5z", filled: false, stroked: true, closed: true),
            .init("M9 11.2v5.6l4.4-2.8z", filled: true, stroked: false, closed: true),
        ],
        .bestTake: [
            .init("M8.5 3h7a2.5 2.5 0 0 1 2.5 2.5v13a2.5 2.5 0 0 1 -2.5 2.5h-7a2.5 2.5 0 0 1 -2.5 -2.5v-13a2.5 2.5 0 0 1 2.5 -2.5z", filled: false, stroked: true, closed: true),
            .init("M12.00 6.80C12.42 10.28 13.72 11.58 17.20 12.00C13.72 12.42 12.42 13.72 12.00 17.20C11.58 13.72 10.28 12.42 6.80 12.00C10.28 11.58 11.58 10.28 12.00 6.80Z", filled: true, stroked: false, closed: true),
        ],
        .delete: [
            .init("M4.5 6.5h15M9.5 6.5v-2h5v2M6.5 6.5l1 12.9A1.5 1.5 0 0 0 9 20.8h6a1.5 1.5 0 0 0 1.5-1.4l1-12.9M10 10.5v6M14 10.5v6", filled: false, stroked: true, closed: false),
        ],
        .favorite: [
            .init("M12 3.8l2.5 5.1 5.6.8-4.1 4 1 5.6-5-2.6-5 2.6 1-5.6-4.1-4 5.6-.8z", filled: false, stroked: true, closed: true),
        ],
        .fitsPlatform: [
            .init("M9.5 3h5a2.5 2.5 0 0 1 2.5 2.5v13a2.5 2.5 0 0 1 -2.5 2.5h-5a2.5 2.5 0 0 1 -2.5 -2.5v-13a2.5 2.5 0 0 1 2.5 -2.5z", filled: false, stroked: true, closed: true),
            .init("M9.6 12.3l1.8 1.8 3.2-3.6", filled: false, stroked: true, closed: false),
        ],
        .play: [
            .init("M8 5.5v13l10.5-6.5z", filled: true, stroked: false, closed: true),
        ],
        .retake: [
            .init("M5 12a7 7 0 1 0 2.1-5", filled: false, stroked: true, closed: false),
            .init("M6.6 3.8L7 7.2l3.4-.5", filled: false, stroked: true, closed: false),
            .init("M10 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0z", filled: true, stroked: false, closed: true),
        ],
        .save: [
            .init("M12 4v10.5M7.8 10.3L12 14.5l4.2-4.2M5 19.5h14", filled: false, stroked: true, closed: false),
        ],
        .share: [
            .init("M12 14.5V3.8M8.2 7.5L12 3.7l3.8 3.8", filled: false, stroked: true, closed: false),
            .init("M8.5 10.5H7A1.5 1.5 0 0 0 5.5 12v7.5A1.5 1.5 0 0 0 7 21h10a1.5 1.5 0 0 0 1.5-1.5V12a1.5 1.5 0 0 0-1.5-1.5h-1.5", filled: false, stroked: true, closed: false),
        ],
        .answer: [
            .init("M5 4.5h14A1.5 1.5 0 0 1 20.5 6v9a1.5 1.5 0 0 1-1.5 1.5h-9l-4.5 3.5v-3.5H5A1.5 1.5 0 0 1 3.5 15V6A1.5 1.5 0 0 1 5 4.5z", filled: false, stroked: true, closed: true),
            .init("M10 7.8L7.8 10l2.2 2.2M8 10h5.5a2.5 2.5 0 0 1 2.5 2.5v.5", filled: false, stroked: true, closed: false),
        ],
        .logbook: [
            .init("M5 18.5V4.5A1.5 1.5 0 0 1 6.5 3H19v15.5H6.5A1.5 1.5 0 0 0 5 20a1 1 0 0 0 1 1h13", filled: false, stroked: true, closed: false),
            .init("M12.50 6.20C12.79 8.61 13.69 9.51 16.10 9.80C13.69 10.09 12.79 10.99 12.50 13.40C12.21 10.99 11.31 10.09 8.90 9.80C11.31 9.51 12.21 8.61 12.50 6.20Z", filled: true, stroked: false, closed: true),
        ],
        .milestone: [
            .init("M6 9.5a6 6 0 1 0 12 0a6 6 0 1 0 -12 0z", filled: false, stroked: true, closed: true),
            .init("M8.8 14.6L7.5 21l4.5-2.2 4.5 2.2-1.3-6.4", filled: false, stroked: true, closed: false),
            .init("M12.00 6.10C12.27 8.38 13.12 9.23 15.40 9.50C13.12 9.77 12.27 10.62 12.00 12.90C11.73 10.62 10.88 9.77 8.60 9.50C10.88 9.23 11.73 8.38 12.00 6.10Z", filled: true, stroked: false, closed: true),
        ],
        .personalize: [
            .init("M8 3.5h9.5a3 3 0 0 1 3 3V16", filled: false, stroked: true, closed: false),
            .init("M7 7.5h6a3.5 3.5 0 0 1 3.5 3.5v6a3.5 3.5 0 0 1 -3.5 3.5h-6a3.5 3.5 0 0 1 -3.5 -3.5v-6a3.5 3.5 0 0 1 3.5 -3.5z", filled: false, stroked: true, closed: true),
            .init("M10.00 10.40C10.29 12.81 11.19 13.71 13.60 14.00C11.19 14.29 10.29 15.19 10.00 17.60C9.71 15.19 8.81 14.29 6.40 14.00C8.81 13.71 9.71 12.81 10.00 10.40Z", filled: true, stroked: false, closed: true),
        ],
        .route: [
            .init("M2.8 17.5a2.2 2.2 0 1 0 4.4 0a2.2 2.2 0 1 0 -4.4 0z", filled: true, stroked: false, closed: true),
            .init("M7.5 16c3.2-.8 4-5 7-5.8", filled: false, stroked: true, closed: false, dash: [0.1, 3]),
            .init("M18.30 3.00C18.62 5.68 19.62 6.68 22.30 7.00C19.62 7.32 18.62 8.32 18.30 11.00C17.98 8.32 16.98 7.32 14.30 7.00C16.98 6.68 17.98 5.68 18.30 3.00Z", filled: true, stroked: false, closed: true),
        ],
        .sendOff: [
            .init("M4 20l7.5-7.5M7.5 21l4.5-4.5M3 16.5L7.5 12", filled: false, stroked: true, closed: false),
            .init("M11.9 8.5a3.6 3.6 0 1 0 7.2 0a3.6 3.6 0 1 0 -7.2 0z", filled: false, stroked: true, closed: true),
        ],
        .topicWorld: [
            .init("M6.8 12a5.2 5.2 0 1 0 10.4 0a5.2 5.2 0 1 0 -10.4 0z", filled: false, stroked: true, closed: true),
            .init("M20.83 8.79A9.4 3.1 -20 0 1 3.17 15.21", filled: false, stroked: true, closed: false),
        ],
        .yourUniverse: [
            .init("M20.59 8.18A9.4 4.2 -24 0 1 3.41 15.82A9.4 4.2 -24 0 1 20.59 8.18", filled: false, stroked: true, closed: false),
            .init("M9.8 12a2.2 2.2 0 1 0 4.4 0a2.2 2.2 0 1 0 -4.4 0z", filled: true, stroked: false, closed: true),
            .init("M1.4 13.84a2.1 2.1 0 1 0 4.2 0a2.1 2.1 0 1 0 -4.2 0z", filled: true, stroked: false, closed: true),
        ],
    ]
}
