#!/usr/bin/env python3
"""Generates Cue Studio/DesignSystem/Tokens/CueIconGeometry.swift from the icon SVGs.

The icons are drawn in code (so the stroke can stay ~1.6 pt at any size, v29 rule): this turns each
SVG element into a path string. Circles and rects become paths with arcs. Run from the repo root:

    python3 design/cue-v29/tools/generate_cue_icons.py [source-dir]

The default source is design/cue-universe-v27/05 Icons/in-app. When the v29 icon boards arrive as SVG, point
this at them: nothing else changes.
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "design/cue-universe-v27/05 Icons/in-app"
ICON_SWIFT = ROOT / "Cue Studio/DesignSystem/Tokens/CueIcon.swift"
OUT = ROOT / "Cue Studio/DesignSystem/Tokens/CueIconGeometry.swift"

# v29: the play triangle is solid, and so is the one inside Takes. (category/name, element index) → filled.
FILLED = {("takes-sharing/play", 0), ("tab-bar/takes", 2)}


def fmt(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text if text not in ("", "-0") else "0"


def circle(el) -> str:
    cx, cy, r = (float(el.get(k)) for k in ("cx", "cy", "r"))
    return f"M{fmt(cx - r)} {fmt(cy)}a{fmt(r)} {fmt(r)} 0 1 0 {fmt(2 * r)} 0a{fmt(r)} {fmt(r)} 0 1 0 {fmt(-2 * r)} 0z"


def rect(el) -> str:
    x, y, w, h = (float(el.get(k)) for k in ("x", "y", "width", "height"))
    rx = float(el.get("rx", 0))
    if rx == 0:
        return f"M{fmt(x)} {fmt(y)}h{fmt(w)}v{fmt(h)}h{fmt(-w)}z"
    return (
        f"M{fmt(x + rx)} {fmt(y)}h{fmt(w - 2 * rx)}a{fmt(rx)} {fmt(rx)} 0 0 1 {fmt(rx)} {fmt(rx)}"
        f"v{fmt(h - 2 * rx)}a{fmt(rx)} {fmt(rx)} 0 0 1 {fmt(-rx)} {fmt(rx)}h{fmt(-(w - 2 * rx))}"
        f"a{fmt(rx)} {fmt(rx)} 0 0 1 {fmt(-rx)} {fmt(-rx)}v{fmt(-(h - 2 * rx))}a{fmt(rx)} {fmt(rx)} 0 0 1 {fmt(rx)} {fmt(-rx)}z"
    )


def elements(svg: Path, key: str):
    root = ET.parse(svg).getroot()
    out = []
    for index, el in enumerate(root):
        tag = el.tag.split("}")[-1]
        d = {"circle": circle, "rect": rect}.get(tag, lambda e: e.get("d"))(el)
        filled = el.get("fill") == "currentColor" or (key, index) in FILLED
        stroked = el.get("stroke") != "none" and not (key, index) in FILLED
        dash = el.get("stroke-dasharray")
        dash_values = [float(v) for v in dash.split()] if dash else None
        out.append((d, filled, stroked, dash_values, d.strip().lower().endswith("z")))
    return out


def main():
    source = ICON_SWIFT.read_text()
    cases = dict(re.findall(r'case (\w+) = "cueicon\.([\w-]+\.[\w-]+)"', source))
    lines = []
    for case, name in cases.items():
        category, icon = name.split(".")
        svg = SOURCE / category / f"{icon}.svg"
        items = elements(svg, f"{category}/{icon}")
        lines.append(f"        .{case}: [")
        for d, filled, stroked, dash, closed in items:
            extras = ""
            if dash:
                extras = f", dash: [{', '.join(fmt(v) for v in dash)}]"
            lines.append(f'            .init("{d}", filled: {str(filled).lower()}, stroked: {str(stroked).lower()}, closed: {str(closed).lower()}{extras}),')
        lines.append("        ],")
    OUT.write_text(HEADER + "\n".join(lines) + "\n    ]\n}\n")
    print(f"{len(cases)} icons → {OUT.relative_to(ROOT)}")


HEADER = '''//
//  CueIconGeometry.swift
//  Cue Studio
//

import SwiftUI

// Generated by design/cue-v29/tools/generate_cue_icons.py from the icon SVGs: do not edit by hand.

/// The shapes of the icon set on its 24 × 24 grid, as SVG path data, and the stroke rule that draws them.
nonisolated enum CueIconGeometry {
    /// One piece of an icon: a path, and whether it is drawn with a fill, a stroke or both.
    struct Element: Sendable {
        let path: Path
        let filled: Bool
        let stroked: Bool
        /// A closed shape can be filled when the icon is "on" (a marked best take).
        let closed: Bool
        /// A dash pattern in grid units (dotted lines); nil for a solid one.
        let dash: [CGFloat]?

        init(_ data: String, filled: Bool, stroked: Bool, closed: Bool, dash: [CGFloat]? = nil) {
            self.path = SVGPathParser.path(from: data)
            self.filled = filled
            self.stroked = stroked
            self.closed = closed
            self.dash = dash
        }
    }

    /// The grid every icon is drawn on.
    static let grid: CGFloat = 24

    /// The stroke stays about 1.6 pt wherever the icon is drawn (v29): `1.6 × 24 / size` grid units, between 1.7
    /// and 3.4 so a big icon doesn't go hairline and a tiny one doesn't clot.
    static let renderedStroke: CGFloat = 1.6
    static let strokeGridRange: ClosedRange<CGFloat> = 1.7...3.4

    /// The stroke in grid units for an icon drawn at `size` points.
    static func strokeInGridUnits(forSize size: CGFloat) -> CGFloat {
        guard size > 0 else { return strokeGridRange.lowerBound }
        return min(strokeGridRange.upperBound, max(strokeGridRange.lowerBound, renderedStroke * grid / size))
    }

    /// The stroke in points for an icon drawn at `size` points.
    static func strokeWidth(forSize size: CGFloat) -> CGFloat {
        strokeInGridUnits(forSize: size) * size / grid
    }

    static func elements(for icon: CueIcon) -> [Element] {
        all[icon] ?? []
    }

    private static let all: [CueIcon: [Element]] = [
'''

main()
